# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

inhibit_all_warnings!

target 'caxjh' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for caxjh

  pod 'Masonry'
  pod 'AFNetworking'
  pod 'MJExtension'
  pod 'MBProgressHUD'
  pod 'Bugly'
  pod 'SDWebImage'
  pod 'MJRefresh'
  pod 'BlocksKit'
  pod 'IQKeyboardManager'
  pod 'DZNEmptyDataSet'
  pod 'NJKWebViewProgress'
  pod 'Toast'
  pod 'DeviceUtil'
  pod 'ZXingObjC', '~> 3.0'
  pod 'Colours'
  pod 'YYCache'
  pod 'RongCloudIM/IMLib', '~> 2.8.3'
  pod 'RongCloudIM/IMKit', '~> 2.8.3'
  pod 'CocoaAsyncSocket'
  pod 'AMapLocation'
  pod 'AMapSearch'
  pod “BaiduMapKit” #百度地图SDK
  # pod 'Toast', '~> 3.1.0'
  target 'caxjhTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'caxjhUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
